version: '3.7'

services:
  ayaqa_dev:
    container_name: ${AYAQA_APP_NAME}
    hostname: ${AYAQA_APP_NAME}
    image: "${AYAQA_PROJECT_NAME}:${AYAQA_PROJECT_TAG}"
    networks:
      - ayaqa_network
    env_file:
        - app.env
    volumes:
      - '${AYAQA_DATA_NAME}:${AYAQA_APP_ROOT_DIR}:rw,delegated'
      - '../setup/:${AYAQA_BOOT_CONFIG_DIR}:rw,cached'
      - '${AYAQA_VOLUME_DIR}:${AYAQA_INFRA_PERSIST_DIR}:rw,cached'
    ports:
      - '${AYAQA_APP_HTTP_PORT}:${AYAQA_WEB_PORT}'
      - '${AYAQA_APP_HTTPS_PORT}:${AYAQA_SECURE_WEB_PORT}'
      - '${AYAQA_APP_XDEBUG_PORT}:${AYAQA_XDEBUG_PORT}'
      - '${AYAQA_APP_SSH_PORT}:${AYAQA_SSH_PORT}'
    tty: true

volumes:
  ayaqa-data:
      name: "${AYAQA_DATA_NAME}"
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ${AYAQA_APP_DIR}

networks:
  ayaqa_network:
      name  : "${AYAQA_NETWORK_NAME}"
      driver: bridge