version: '3.7'

services:
  ayaqa_dev:
    container_name: ${AYAQA_APP_NAME}
    hostname: ${AYAQA_APP_NAME}
    image: "${AYAQA_INFRA_IMAGE_NAME}:${AYAQA_INFRA_IMAGE_TAG}"
    networks:
      - ayaqa_network
    env_file:
        - app.env
    volumes:
      - '${AYAQA_DATA_NAME}:${AYAQA_APP_VOLUME_DIR}:rw'
      - '../scripts/:${AYAQA_INFRA_ON_BOOT_BASH_SCRIPTS_VOLUME}:rw,cached'
      - '../confs/:${AYAQA_INFRA_ON_BOOT_CONFS_VOLUME}:rw,cached'
      - '${AYAQA_VOLUME_NAME}:${AYAQA_INFRA_VOLUME_DIR}:rw,cached'
    ports:
      - '${AYAQA_APP_HTTP_PORT}:${AYAQA_WEB_PORT}'
      - '${AYAQA_APP_HTTPS_PORT}:${AYAQA_SECURE_WEB_PORT}'
      - '${AYAQA_APP_XDEBUG_PORT}:${AYAQA_XDEBUG_PORT}'
      - '${AYAQA_APP_SSH_PORT}:${AYAQA_SSH_PORT}'
    tty: true

volumes:
  ayaqa-code:
      name: "${AYAQA_DATA_NAME}"
      driver: local
      driver_opts:
        o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
        type: nfs
        device: ":${AYAQA_APP_DIR}"

  ayaqa-volume:
    name: "${AYAQA_VOLUME_NAME}"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${AYAQA_VOLUME_DIR}

networks:
  ayaqa_network:
      name  : "${AYAQA_NETWORK_NAME}"
      driver: bridge
